name: Deploy to Lightsail

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Build and run tests
        run: |
          npm install
          npm test

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region

      - name: Build and push Docker image
        run: |
          docker build -t your-image-name .
          docker tag your-image-name:latest your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/your-image-name:latest
          docker push your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/your-image-name:latest

      - name: Deploy to Lightsail
        run: |
          # Your deployment script here to launch the Docker container on Lightsail